name: ci_workflow
on: 
    pull_request: {}
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pip install requirements.txt
      - run: pytest test_file.py
