name: Increment Tag

on:
  push:
    branches:
      - 'stable-*'

jobs:
  increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Determine branch name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV

      - name: Get latest matching tag
        id: get_latest_matching_tag
        run: |
          branch_name="${{ env.BRANCH_NAME }}"

      - name: Calculate New Tag
        id: calculate_new_tag
        run: |
          branch_name="${{ env.BRANCH_NAME }}"
          latest_tag="${{ env.TAG }}"
          if [ "$latest_tag" == "none" ]; then
            new_tag="${branch_name}.0"
          else
            version="${latest_tag##$branch_name}"
            version=$((version + 1))
            new_tag="${branch_name}${version}"
          fi
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create new tag
        id: create_new_tag
        run: |
          new_tag="${{ env.NEW_TAG }}"
          git tag -a "$new_tag" -m "Version $new_tag"
          git push origin --tags
