name: Increment Tag

on:
  push:
    branches:
      - 'stable-*'

jobs:
  increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get latest matching tag
        id: get_latest_matching_tag
        run: |
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          latest_tag=$(git describe --tags --abbrev=0 --match "$branch_name*" 2>/dev/null)
          if [ -z "$latest_tag" ]; then
            echo "TAG=none" >> $GITHUB_OUTPUT
          else
            echo "TAG=${latest_tag}" >> $GITHUB_OUTPUT
          fi

      - name: Calculate New Tag
        id: calculate_new_tag
        run: |
          branch_name=$(echo $GITHUB_REF | sed 's/refs\/heads\///')
          latest_tag="${{ steps.get_latest_matching_tag.outputs.TAG }}"
          if [ "$latest_tag" == "none" ]; then
            new_tag="${branch_name}.0"
          else
            version="${latest_tag##$branch_name}"
            version=$((version + 1))
            new_tag="${branch_name}${version}"
          fi
          echo "NEW_TAG=${new_tag}" >> $GITHUB_OUTPUT

      - name: Create new tag
        id: create_new_tag
        run: |
          new_tag="${{ steps.calculate_new_tag.outputs.NEW_TAG }}"
          git tag -a "$new_tag" -m "Version $new_tag"
          git push origin --tags
