name: Increment Tag

on:
  push:
    branches:
      - 'stable-*'

jobs:
  increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Git Identity
        run: |
          git config user.email "tag-bot@hypernative.io"
          git config user.name "tag-bot"

      - name: Determine branch name
        id: branch_name
        run: echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\/stable\-//')" >> $GITHUB_ENV

      - name: Get latest matching tag
        id: get_latest_matching_tag
        run: |
          git fetch --tags
          branch_name="${{ env.BRANCH_NAME }}"
          latest_tag=$(git tag -l | grep -E "^v$branch_name\.[0-9]+$" | sort -r | head -n 1)
          if [ -z "$latest_tag" ]; then
            echo "TAG=none" >> $GITHUB_ENV
          else
            echo "TAG=$latest_tag" >> $GITHUB_ENV
          fi

      - name: Calculate New Tag
        id: calculate_new_tag
        run: |
          branch_name="${{ env.BRANCH_NAME }}"
          latest_tag="${{ env.TAG }}"
          echo $latest_tag
          if [ "$latest_tag" == "none" ]; then
            new_tag="v${branch_name}.0"
          else
            version="${latest_tag##v$branch_name}"
            version=$((version + 1))
            new_tag="v${branch_name}${version}"
          fi
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create new tag
        id: create_new_tag
        run: |
          new_tag="${{ env.NEW_TAG }}"
          git tag -a "$new_tag" -m "Version $new_tag"
          git push origin --tags
